/**
 * A list of phrases to generate random text from.
 */
export const phrases = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.',
  'Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.',
  'Integer in mauris eu nibh euismod gravida.',
  'Duis ac tellus et risus vulputate vehicula.',
  'Donec lobortis risus a elit. Etiam tempor.',
  'Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam.',
  'Maecenas fermentum consequat mi. Donec fermentum.',
  'Pellentesque malesuada nulla a mi.',
  'Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.',
  'Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat.',
  'Cras mollis scelerisque nunc. Nullam arcu.',
  'Aliquam erat volutpat. Duis ac turpis.',
  'Integer rutrum ante eu lacus.',
  'Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque.',
  'Vivamus eget nibh. Etiam cursus leo vel metus.',
  'Nulla facilisi. Aenean nec eros.',
  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sollicitudin velit sed leo.',
  'Ut pharetra augue nec augue.',
  'Nam elit agna, endrerit sit amet, tincidunt ac, viverra sed, nulla.',
  'Donec porta diam eu massa.',
  'Quisque diam lorem, interdum vitae, dapibus ac, scelerisque vitae, pede.',
  'Donec eget tellus non erat lacinia fermentum.',
  'Donec in velit vel ipsum auctor pulvinar.',
  'Vestibulum iaculis lacinia est.',
  'Proin dictum elementum velit.',
  'Fusce euismod consequat ante.',
  'Pellentesque sed dolor. Aliquam congue fermentum nisl.',
  'Mauris accumsan nulla vel diam.',
  'Sed in lacus ut enim adipiscing aliquet.',
  'Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula.',
  'Aliquam dapibus tincidunt metus.',
  'Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem.',
  'Vestibulum sed ante. Donec sagittis euismod purus.',
  'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
  'Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
  'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
  'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
  'Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
  'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.',
  'Maecenas a justo iaculis dolor venenatis luctus.',
  'Donec dapibus semper elit, ut ornare enim ullamcorper vel.',
  'Sed finibus, dui ac viverra lobortis, arcu neque consectetur turpis, a varius enim augue fringilla urna.',
  'Maecenas ultrices ac ipsum nec tincidunt.',
  'Etiam tincidunt consectetur purus quis scelerisque; Duis eget diam ut mi condimentum imperdiet.',
  'Nunc urna purus, pharetra consequat egestas eu, pellentesque eu neque.',
  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.',
  'Donec ultricies eleifend sollicitudin; Vivamus sollicitudin odio purus, ut malesuada metus facilisis et.',
  'Morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.',
  'Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.',
  'Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.',
  'Phasellus ultrices nulla quis nibh. Quisque a lectus.',
  'Donec consectetuer ligula vulputate sem tristique cursus.',
  'Nam magna quam, egestas nec, malesuada nec, dignissim nec, ligula.',
  'Nulla facilisi. Donec nec diam.',
  'Vestibulum lacinia sollicitudin lorem.',
  'Maecenas sollicitudin. Nulla eget sem vitae eros pharetra viverra.',
  'Nam posuere accumsan porta.',
  'Integer id magna at metus pretium congue.',
  'Maecenas ut justo et neque pretium aliquet.',
  'Curabitur nec arcu. Donec sollicitudin mi sit amet mauris.',
  'Suspendisse ultrices, nisi eget vehicula posuere, felis nisi suscipit massa, nec luctus nulla neque id augue.',
  'Fusce bibendum, risus nec fringilla auctor, est magna bibendum ligula, in bibendum risus orci sit amet ante.',
  'In hac habitasse platea dictumst.',
  'Sed adipiscing ornare risus. Morbi est est, blandit sit amet, sagittis vel, euismod vel, velit.',
  'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'In dui magna, posuere eget, vestibulum et, tempor auctor, justo.',
  'In ac felis quis tortor malesuada pretium.',
  'Vivamus consectetuer hendrerit lacus.',
  'Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet.',
  'Sed volutpat nisl ac risus facilisis, vitae auctor eros euismod.',
  'Fusce in neque vel nisi vulputate consequat.',
  'Suspendisse euismod, elit vel elementum venenatis, urna lacus ultrices velit, sed ornare arcu turpis ut nunc.'
];
